// 插件与宿主之间的 gRPC 线上契约（SSOT - Single Source of Truth）。
//
// 该文件自 gametrace/pkg/plugin/proto/ 迁入 SDK。迁移前 gametrace 与 SDK 各自持有一份
// 逐字节相同的生成代码，但它们在 protobuf 全局注册表中登记的是同一个文件路径，
// 一旦被链接进同一个二进制就会 panic（file already registered），
// 使宿主根本无法复用 SDK 的任何 proto 相关代码。现在只此一份。
//
// 重新生成：make proto（输出 paths=source_relative 到 proto/）。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.4
// source: proto/plugin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifest      []byte                 `protobuf:"bytes,2,opt,name=manifest,proto3" json:"manifest,omitempty"` // plugin.yaml 原文（主程序 parse）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetManifest() []byte {
	if x != nil {
		return x.Manifest
	}
	return nil
}

type RegisterResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	InstanceId           string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`                                  // 主程序分配的实例 ID
	HeartbeatIntervalSec int32                  `protobuf:"varint,2,opt,name=heartbeat_interval_sec,json=heartbeatIntervalSec,proto3" json:"heartbeat_interval_sec,omitempty"` // 主程序要求的心跳间隔
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *RegisterResponse) GetHeartbeatIntervalSec() int32 {
	if x != nil {
		return x.HeartbeatIntervalSec
	}
	return 0
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{3}
}

type DeregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterRequest) Reset() {
	*x = DeregisterRequest{}
	mi := &file_proto_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterRequest) ProtoMessage() {}

func (x *DeregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterRequest.ProtoReflect.Descriptor instead.
func (*DeregisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *DeregisterRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type DeregisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterResponse) Reset() {
	*x = DeregisterResponse{}
	mi := &file_proto_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterResponse) ProtoMessage() {}

func (x *DeregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterResponse.ProtoReflect.Descriptor instead.
func (*DeregisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{5}
}

type DecodeRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	SessionId    string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ProtocolHint string                 `protobuf:"bytes,2,opt,name=protocol_hint,json=protocolHint,proto3" json:"protocol_hint,omitempty"`
	Payload      []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	LinkType     int32                  `protobuf:"varint,4,opt,name=link_type,json=linkType,proto3" json:"link_type,omitempty"`
	InputId      string                 `protobuf:"bytes,5,opt,name=input_id,json=inputId,proto3" json:"input_id,omitempty"`    // 本次解码输入的唯一标识，复用 packet_id
	PacketId     string                 `protobuf:"bytes,6,opt,name=packet_id,json=packetId,proto3" json:"packet_id,omitempty"` // 原始抓包 ID
	FlowId       string                 `protobuf:"bytes,7,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`       // 五元组流 ID，核心生成
	Src          string                 `protobuf:"bytes,8,opt,name=src,proto3" json:"src,omitempty"`                           // "ip:port"
	Dst          string                 `protobuf:"bytes,9,opt,name=dst,proto3" json:"dst,omitempty"`                           // "ip:port"
	// direction is inferred by the core from the 5-tuple; the plugin may
	// override it via _meta.direction in the payload.
	Direction     string `protobuf:"bytes,10,opt,name=direction,proto3" json:"direction,omitempty"`
	TimestampNs   int64  `protobuf:"varint,11,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"` // 包时间戳（Unix ns）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecodeRequest) Reset() {
	*x = DecodeRequest{}
	mi := &file_proto_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodeRequest) ProtoMessage() {}

func (x *DecodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodeRequest.ProtoReflect.Descriptor instead.
func (*DecodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *DecodeRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DecodeRequest) GetProtocolHint() string {
	if x != nil {
		return x.ProtocolHint
	}
	return ""
}

func (x *DecodeRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DecodeRequest) GetLinkType() int32 {
	if x != nil {
		return x.LinkType
	}
	return 0
}

func (x *DecodeRequest) GetInputId() string {
	if x != nil {
		return x.InputId
	}
	return ""
}

func (x *DecodeRequest) GetPacketId() string {
	if x != nil {
		return x.PacketId
	}
	return ""
}

func (x *DecodeRequest) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

func (x *DecodeRequest) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *DecodeRequest) GetDst() string {
	if x != nil {
		return x.Dst
	}
	return ""
}

func (x *DecodeRequest) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *DecodeRequest) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

// DecodeResponseV2 represents a single decoded result for one input_id.
// The plugin sends zero or more result messages, followed by one message
// with done=true to mark the end of results for that input_id.
// If error is set, this result represents a decode failure.
type DecodeResponseV2 struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	InputId          string                 `protobuf:"bytes,1,opt,name=input_id,json=inputId,proto3" json:"input_id,omitempty"`                              // 对应 DecodeRequest.input_id
	Done             bool                   `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`                                                  // true 表示该 input_id 的结果已全部发完
	EventType        string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`                        // 当 done=true 时为空
	PayloadMsgpack   []byte                 `protobuf:"bytes,5,opt,name=payload_msgpack,json=payloadMsgpack,proto3" json:"payload_msgpack,omitempty"`         // MsgPack 编码的 Value
	Error            string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`                                                 // 错误信息
	CorrelationKey   string                 `protobuf:"bytes,7,opt,name=correlation_key,json=correlationKey,proto3" json:"correlation_key,omitempty"`         // 业务关联键
	CausationInputId string                 `protobuf:"bytes,8,opt,name=causation_input_id,json=causationInputId,proto3" json:"causation_input_id,omitempty"` // 指向导致本结果的 input_id
	MetaMsgpack      []byte                 `protobuf:"bytes,9,opt,name=meta_msgpack,json=metaMsgpack,proto3" json:"meta_msgpack,omitempty"`                  // 可选：MsgPack 编码的 Meta Value（direction/msg_name/role 等元信息）
	AnalysisMsgpack  []byte                 `protobuf:"bytes,10,opt,name=analysis_msgpack,json=analysisMsgpack,proto3" json:"analysis_msgpack,omitempty"`     // 可选：MsgPack 编码的 Analysis Value（_state_changes/entity 等分析）
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DecodeResponseV2) Reset() {
	*x = DecodeResponseV2{}
	mi := &file_proto_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecodeResponseV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodeResponseV2) ProtoMessage() {}

func (x *DecodeResponseV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodeResponseV2.ProtoReflect.Descriptor instead.
func (*DecodeResponseV2) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *DecodeResponseV2) GetInputId() string {
	if x != nil {
		return x.InputId
	}
	return ""
}

func (x *DecodeResponseV2) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *DecodeResponseV2) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *DecodeResponseV2) GetPayloadMsgpack() []byte {
	if x != nil {
		return x.PayloadMsgpack
	}
	return nil
}

func (x *DecodeResponseV2) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DecodeResponseV2) GetCorrelationKey() string {
	if x != nil {
		return x.CorrelationKey
	}
	return ""
}

func (x *DecodeResponseV2) GetCausationInputId() string {
	if x != nil {
		return x.CausationInputId
	}
	return ""
}

func (x *DecodeResponseV2) GetMetaMsgpack() []byte {
	if x != nil {
		return x.MetaMsgpack
	}
	return nil
}

func (x *DecodeResponseV2) GetAnalysisMsgpack() []byte {
	if x != nil {
		return x.AnalysisMsgpack
	}
	return nil
}

// TunnelFrame 是 Connect 双向流上的帧。
// 流的开启是隐式的：某 stream_id 的第一个 request 帧即开流。
type TunnelFrame struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	StreamId uint32                 `protobuf:"varint,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*TunnelFrame_Request
	//	*TunnelFrame_HalfClose
	//	*TunnelFrame_Response
	//	*TunnelFrame_End
	//	*TunnelFrame_Reset_
	Payload       isTunnelFrame_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelFrame) Reset() {
	*x = TunnelFrame{}
	mi := &file_proto_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelFrame) ProtoMessage() {}

func (x *TunnelFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelFrame.ProtoReflect.Descriptor instead.
func (*TunnelFrame) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *TunnelFrame) GetStreamId() uint32 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

func (x *TunnelFrame) GetPayload() isTunnelFrame_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TunnelFrame) GetRequest() []byte {
	if x != nil {
		if x, ok := x.Payload.(*TunnelFrame_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *TunnelFrame) GetHalfClose() bool {
	if x != nil {
		if x, ok := x.Payload.(*TunnelFrame_HalfClose); ok {
			return x.HalfClose
		}
	}
	return false
}

func (x *TunnelFrame) GetResponse() []byte {
	if x != nil {
		if x, ok := x.Payload.(*TunnelFrame_Response); ok {
			return x.Response
		}
	}
	return nil
}

func (x *TunnelFrame) GetEnd() *StreamEnd {
	if x != nil {
		if x, ok := x.Payload.(*TunnelFrame_End); ok {
			return x.End
		}
	}
	return nil
}

func (x *TunnelFrame) GetReset_() *StreamReset {
	if x != nil {
		if x, ok := x.Payload.(*TunnelFrame_Reset_); ok {
			return x.Reset_
		}
	}
	return nil
}

type isTunnelFrame_Payload interface {
	isTunnelFrame_Payload()
}

type TunnelFrame_Request struct {
	Request []byte `protobuf:"bytes,2,opt,name=request,proto3,oneof"` // server→plugin: marshaled DecodeRequest
}

type TunnelFrame_HalfClose struct {
	HalfClose bool `protobuf:"varint,3,opt,name=half_close,json=halfClose,proto3,oneof"` // server→plugin: 该逻辑流的请求侧关闭（对应 CloseSend）
}

type TunnelFrame_Response struct {
	Response []byte `protobuf:"bytes,4,opt,name=response,proto3,oneof"` // plugin→server: marshaled DecodeResponseV2
}

type TunnelFrame_End struct {
	End *StreamEnd `protobuf:"bytes,5,opt,name=end,proto3,oneof"` // plugin→server: 流结束（error 空 = 正常 EOF）
}

type TunnelFrame_Reset_ struct {
	Reset_ *StreamReset `protobuf:"bytes,6,opt,name=reset,proto3,oneof"` // server→plugin: 取消该逻辑流
}

func (*TunnelFrame_Request) isTunnelFrame_Payload() {}

func (*TunnelFrame_HalfClose) isTunnelFrame_Payload() {}

func (*TunnelFrame_Response) isTunnelFrame_Payload() {}

func (*TunnelFrame_End) isTunnelFrame_Payload() {}

func (*TunnelFrame_Reset_) isTunnelFrame_Payload() {}

type StreamEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"` // 非空表示该逻辑流以错误结束
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEnd) Reset() {
	*x = StreamEnd{}
	mi := &file_proto_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEnd) ProtoMessage() {}

func (x *StreamEnd) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEnd.ProtoReflect.Descriptor instead.
func (*StreamEnd) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *StreamEnd) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StreamReset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamReset) Reset() {
	*x = StreamReset{}
	mi := &file_proto_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamReset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamReset) ProtoMessage() {}

func (x *StreamReset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamReset.ProtoReflect.Descriptor instead.
func (*StreamReset) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *StreamReset) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_proto_plugin_proto protoreflect.FileDescriptor

const file_proto_plugin_proto_rawDesc = "" +
	"\n" +
	"\x12proto/plugin.proto\x12\x06plugin\"9\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\bmanifest\x18\x02 \x01(\fR\bmanifestJ\x04\b\x01\x10\x02J\x04\b\x03\x10\x04\"i\n" +
	"\x10RegisterResponse\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x124\n" +
	"\x16heartbeat_interval_sec\x18\x02 \x01(\x05R\x14heartbeatIntervalSec\"3\n" +
	"\x10HeartbeatRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\"\x13\n" +
	"\x11HeartbeatResponse\"4\n" +
	"\x11DeregisterRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\"\x14\n" +
	"\x12DeregisterResponse\"\xc0\x02\n" +
	"\rDecodeRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rprotocol_hint\x18\x02 \x01(\tR\fprotocolHint\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1b\n" +
	"\tlink_type\x18\x04 \x01(\x05R\blinkType\x12\x19\n" +
	"\binput_id\x18\x05 \x01(\tR\ainputId\x12\x1b\n" +
	"\tpacket_id\x18\x06 \x01(\tR\bpacketId\x12\x17\n" +
	"\aflow_id\x18\a \x01(\tR\x06flowId\x12\x10\n" +
	"\x03src\x18\b \x01(\tR\x03src\x12\x10\n" +
	"\x03dst\x18\t \x01(\tR\x03dst\x12\x1c\n" +
	"\tdirection\x18\n" +
	" \x01(\tR\tdirection\x12!\n" +
	"\ftimestamp_ns\x18\v \x01(\x03R\vtimestampNs\"\xc4\x02\n" +
	"\x10DecodeResponseV2\x12\x19\n" +
	"\binput_id\x18\x01 \x01(\tR\ainputId\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12'\n" +
	"\x0fpayload_msgpack\x18\x05 \x01(\fR\x0epayloadMsgpack\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12'\n" +
	"\x0fcorrelation_key\x18\a \x01(\tR\x0ecorrelationKey\x12,\n" +
	"\x12causation_input_id\x18\b \x01(\tR\x10causationInputId\x12!\n" +
	"\fmeta_msgpack\x18\t \x01(\fR\vmetaMsgpack\x12)\n" +
	"\x10analysis_msgpack\x18\n" +
	" \x01(\fR\x0fanalysisMsgpack\"\xe4\x01\n" +
	"\vTunnelFrame\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\rR\bstreamId\x12\x1a\n" +
	"\arequest\x18\x02 \x01(\fH\x00R\arequest\x12\x1f\n" +
	"\n" +
	"half_close\x18\x03 \x01(\bH\x00R\thalfClose\x12\x1c\n" +
	"\bresponse\x18\x04 \x01(\fH\x00R\bresponse\x12%\n" +
	"\x03end\x18\x05 \x01(\v2\x11.plugin.StreamEndH\x00R\x03end\x12+\n" +
	"\x05reset\x18\x06 \x01(\v2\x13.plugin.StreamResetH\x00R\x05resetB\t\n" +
	"\apayload\"!\n" +
	"\tStreamEnd\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"%\n" +
	"\vStreamReset\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason2\x8f\x02\n" +
	"\x0ePluginRegistry\x12=\n" +
	"\bRegister\x12\x17.plugin.RegisterRequest\x1a\x18.plugin.RegisterResponse\x12@\n" +
	"\tHeartbeat\x12\x18.plugin.HeartbeatRequest\x1a\x19.plugin.HeartbeatResponse\x12C\n" +
	"\n" +
	"Deregister\x12\x19.plugin.DeregisterRequest\x1a\x1a.plugin.DeregisterResponse\x127\n" +
	"\aConnect\x12\x13.plugin.TunnelFrame\x1a\x13.plugin.TunnelFrame(\x010\x012J\n" +
	"\aDecoder\x12?\n" +
	"\bDecodeV2\x12\x15.plugin.DecodeRequest\x1a\x18.plugin.DecodeResponseV2(\x010\x01B1Z/github.com/OwnSecurityGuard/gametrace/sdk/protob\x06proto3"

var (
	file_proto_plugin_proto_rawDescOnce sync.Once
	file_proto_plugin_proto_rawDescData []byte
)

func file_proto_plugin_proto_rawDescGZIP() []byte {
	file_proto_plugin_proto_rawDescOnce.Do(func() {
		file_proto_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_plugin_proto_rawDesc), len(file_proto_plugin_proto_rawDesc)))
	})
	return file_proto_plugin_proto_rawDescData
}

var file_proto_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_plugin_proto_goTypes = []any{
	(*RegisterRequest)(nil),    // 0: plugin.RegisterRequest
	(*RegisterResponse)(nil),   // 1: plugin.RegisterResponse
	(*HeartbeatRequest)(nil),   // 2: plugin.HeartbeatRequest
	(*HeartbeatResponse)(nil),  // 3: plugin.HeartbeatResponse
	(*DeregisterRequest)(nil),  // 4: plugin.DeregisterRequest
	(*DeregisterResponse)(nil), // 5: plugin.DeregisterResponse
	(*DecodeRequest)(nil),      // 6: plugin.DecodeRequest
	(*DecodeResponseV2)(nil),   // 7: plugin.DecodeResponseV2
	(*TunnelFrame)(nil),        // 8: plugin.TunnelFrame
	(*StreamEnd)(nil),          // 9: plugin.StreamEnd
	(*StreamReset)(nil),        // 10: plugin.StreamReset
}
var file_proto_plugin_proto_depIdxs = []int32{
	9,  // 0: plugin.TunnelFrame.end:type_name -> plugin.StreamEnd
	10, // 1: plugin.TunnelFrame.reset:type_name -> plugin.StreamReset
	0,  // 2: plugin.PluginRegistry.Register:input_type -> plugin.RegisterRequest
	2,  // 3: plugin.PluginRegistry.Heartbeat:input_type -> plugin.HeartbeatRequest
	4,  // 4: plugin.PluginRegistry.Deregister:input_type -> plugin.DeregisterRequest
	8,  // 5: plugin.PluginRegistry.Connect:input_type -> plugin.TunnelFrame
	6,  // 6: plugin.Decoder.DecodeV2:input_type -> plugin.DecodeRequest
	1,  // 7: plugin.PluginRegistry.Register:output_type -> plugin.RegisterResponse
	3,  // 8: plugin.PluginRegistry.Heartbeat:output_type -> plugin.HeartbeatResponse
	5,  // 9: plugin.PluginRegistry.Deregister:output_type -> plugin.DeregisterResponse
	8,  // 10: plugin.PluginRegistry.Connect:output_type -> plugin.TunnelFrame
	7,  // 11: plugin.Decoder.DecodeV2:output_type -> plugin.DecodeResponseV2
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_plugin_proto_init() }
func file_proto_plugin_proto_init() {
	if File_proto_plugin_proto != nil {
		return
	}
	file_proto_plugin_proto_msgTypes[8].OneofWrappers = []any{
		(*TunnelFrame_Request)(nil),
		(*TunnelFrame_HalfClose)(nil),
		(*TunnelFrame_Response)(nil),
		(*TunnelFrame_End)(nil),
		(*TunnelFrame_Reset_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_plugin_proto_rawDesc), len(file_proto_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_plugin_proto_goTypes,
		DependencyIndexes: file_proto_plugin_proto_depIdxs,
		MessageInfos:      file_proto_plugin_proto_msgTypes,
	}.Build()
	File_proto_plugin_proto = out.File
	file_proto_plugin_proto_goTypes = nil
	file_proto_plugin_proto_depIdxs = nil
}
