// 插件与宿主之间的 gRPC 线上契约（SSOT - Single Source of Truth）。
//
// 该文件自 gametrace/pkg/plugin/proto/ 迁入 SDK。迁移前 gametrace 与 SDK 各自持有一份
// 逐字节相同的生成代码，但它们在 protobuf 全局注册表中登记的是同一个文件路径，
// 一旦被链接进同一个二进制就会 panic（file already registered），
// 使宿主根本无法复用 SDK 的任何 proto 相关代码。现在只此一份。
//
// 重新生成：make proto（输出 paths=source_relative 到 proto/）。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.4
// source: proto/plugin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginRegistry_Register_FullMethodName   = "/plugin.PluginRegistry/Register"
	PluginRegistry_Heartbeat_FullMethodName  = "/plugin.PluginRegistry/Heartbeat"
	PluginRegistry_Deregister_FullMethodName = "/plugin.PluginRegistry/Deregister"
	PluginRegistry_Connect_FullMethodName    = "/plugin.PluginRegistry/Connect"
)

// PluginRegistryClient is the client API for PluginRegistry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PluginRegistry 由主程序实现，插件主动注册。
type PluginRegistryClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	Deregister(ctx context.Context, in *DeregisterRequest, opts ...grpc.CallOption) (*DeregisterResponse, error)
	// Connect 由注册成功的插件拨出：主程序经此双向流把 DecodeRequest 以帧形式
	// 转发给插件，插件用 TunnelFrame 应答。这是唯一的解码通道——主程序不回拨插件。
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TunnelFrame, TunnelFrame], error)
}

type pluginRegistryClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginRegistryClient(cc grpc.ClientConnInterface) PluginRegistryClient {
	return &pluginRegistryClient{cc}
}

func (c *pluginRegistryClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, PluginRegistry_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginRegistryClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, PluginRegistry_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginRegistryClient) Deregister(ctx context.Context, in *DeregisterRequest, opts ...grpc.CallOption) (*DeregisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeregisterResponse)
	err := c.cc.Invoke(ctx, PluginRegistry_Deregister_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginRegistryClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TunnelFrame, TunnelFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PluginRegistry_ServiceDesc.Streams[0], PluginRegistry_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TunnelFrame, TunnelFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PluginRegistry_ConnectClient = grpc.BidiStreamingClient[TunnelFrame, TunnelFrame]

// PluginRegistryServer is the server API for PluginRegistry service.
// All implementations must embed UnimplementedPluginRegistryServer
// for forward compatibility.
//
// PluginRegistry 由主程序实现，插件主动注册。
type PluginRegistryServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	Deregister(context.Context, *DeregisterRequest) (*DeregisterResponse, error)
	// Connect 由注册成功的插件拨出：主程序经此双向流把 DecodeRequest 以帧形式
	// 转发给插件，插件用 TunnelFrame 应答。这是唯一的解码通道——主程序不回拨插件。
	Connect(grpc.BidiStreamingServer[TunnelFrame, TunnelFrame]) error
	mustEmbedUnimplementedPluginRegistryServer()
}

// UnimplementedPluginRegistryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginRegistryServer struct{}

func (UnimplementedPluginRegistryServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedPluginRegistryServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedPluginRegistryServer) Deregister(context.Context, *DeregisterRequest) (*DeregisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Deregister not implemented")
}
func (UnimplementedPluginRegistryServer) Connect(grpc.BidiStreamingServer[TunnelFrame, TunnelFrame]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedPluginRegistryServer) mustEmbedUnimplementedPluginRegistryServer() {}
func (UnimplementedPluginRegistryServer) testEmbeddedByValue()                        {}

// UnsafePluginRegistryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginRegistryServer will
// result in compilation errors.
type UnsafePluginRegistryServer interface {
	mustEmbedUnimplementedPluginRegistryServer()
}

func RegisterPluginRegistryServer(s grpc.ServiceRegistrar, srv PluginRegistryServer) {
	// If the following call panics, it indicates UnimplementedPluginRegistryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginRegistry_ServiceDesc, srv)
}

func _PluginRegistry_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginRegistryServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginRegistry_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginRegistryServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginRegistry_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginRegistryServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginRegistry_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginRegistryServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginRegistry_Deregister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeregisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginRegistryServer).Deregister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginRegistry_Deregister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginRegistryServer).Deregister(ctx, req.(*DeregisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginRegistry_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PluginRegistryServer).Connect(&grpc.GenericServerStream[TunnelFrame, TunnelFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PluginRegistry_ConnectServer = grpc.BidiStreamingServer[TunnelFrame, TunnelFrame]

// PluginRegistry_ServiceDesc is the grpc.ServiceDesc for PluginRegistry service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginRegistry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugin.PluginRegistry",
	HandlerType: (*PluginRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _PluginRegistry_Register_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _PluginRegistry_Heartbeat_Handler,
		},
		{
			MethodName: "Deregister",
			Handler:    _PluginRegistry_Deregister_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _PluginRegistry_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/plugin.proto",
}

const (
	Decoder_DecodeV2_FullMethodName = "/plugin.Decoder/DecodeV2"
)

// DecoderClient is the client API for Decoder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Decoder 是解码服务的逻辑接口：插件侧由 SDK 实现，注册后经 Connect 隧道暴露，
// 主程序不再直接拨号插件的任何本地端点。
type DecoderClient interface {
	// DecodeV2 是新版解码接口，返回结构化的 EventV2 数据
	DecodeV2(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DecodeRequest, DecodeResponseV2], error)
}

type decoderClient struct {
	cc grpc.ClientConnInterface
}

func NewDecoderClient(cc grpc.ClientConnInterface) DecoderClient {
	return &decoderClient{cc}
}

func (c *decoderClient) DecodeV2(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DecodeRequest, DecodeResponseV2], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Decoder_ServiceDesc.Streams[0], Decoder_DecodeV2_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DecodeRequest, DecodeResponseV2]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Decoder_DecodeV2Client = grpc.BidiStreamingClient[DecodeRequest, DecodeResponseV2]

// DecoderServer is the server API for Decoder service.
// All implementations must embed UnimplementedDecoderServer
// for forward compatibility.
//
// Decoder 是解码服务的逻辑接口：插件侧由 SDK 实现，注册后经 Connect 隧道暴露，
// 主程序不再直接拨号插件的任何本地端点。
type DecoderServer interface {
	// DecodeV2 是新版解码接口，返回结构化的 EventV2 数据
	DecodeV2(grpc.BidiStreamingServer[DecodeRequest, DecodeResponseV2]) error
	mustEmbedUnimplementedDecoderServer()
}

// UnimplementedDecoderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDecoderServer struct{}

func (UnimplementedDecoderServer) DecodeV2(grpc.BidiStreamingServer[DecodeRequest, DecodeResponseV2]) error {
	return status.Error(codes.Unimplemented, "method DecodeV2 not implemented")
}
func (UnimplementedDecoderServer) mustEmbedUnimplementedDecoderServer() {}
func (UnimplementedDecoderServer) testEmbeddedByValue()                 {}

// UnsafeDecoderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DecoderServer will
// result in compilation errors.
type UnsafeDecoderServer interface {
	mustEmbedUnimplementedDecoderServer()
}

func RegisterDecoderServer(s grpc.ServiceRegistrar, srv DecoderServer) {
	// If the following call panics, it indicates UnimplementedDecoderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Decoder_ServiceDesc, srv)
}

func _Decoder_DecodeV2_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DecoderServer).DecodeV2(&grpc.GenericServerStream[DecodeRequest, DecodeResponseV2]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Decoder_DecodeV2Server = grpc.BidiStreamingServer[DecodeRequest, DecodeResponseV2]

// Decoder_ServiceDesc is the grpc.ServiceDesc for Decoder service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Decoder_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugin.Decoder",
	HandlerType: (*DecoderServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DecodeV2",
			Handler:       _Decoder_DecodeV2_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/plugin.proto",
}
